---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
      username: vagrant
      password: vagrant
suites:
  - name: default
    run_list:
      - recipe[doare-base::default]
    attributes:
