---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu/trusty64

suites:
  - name: default
    run_list:
      - recipe[doare-base::default]
      - recipe[doare-php::default]
    attributes:
